name: android-ndk-native
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/android-ndk-native.yml'
      - 'android-ndk-native/*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_buildx.yml'
      - '.github/workflows/android-ndk-native.yml'
      - 'android-ndk-native/*'

jobs:
  android-ndk-r27d:
    secrets: inherit
    uses: ./.github/workflows/_buildx.yml
    with:
      tagname: 'android-ndk-r27d'
      build-args: |
        NDK_VERSION=r27d
        NDK_EXTRACT_SUFFIX=
